version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: bell24h-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # N8N Configuration
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_ADMIN_PASSWORD:-bell24h-n8n-2024}
      
      # Database Configuration
      - DB_TYPE=postgresql
      - DB_POSTGRESDB_HOST=${N8N_DB_HOST:-postgres}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${N8N_DB_NAME:-n8n}
      - DB_POSTGRESDB_USER=${N8N_DB_USER:-n8n}
      - DB_POSTGRESDB_PASSWORD=${N8N_DB_PASSWORD:-n8n-password}
      
      # Application Configuration
      - N8N_HOST=${N8N_HOST:-n8n.bell24h.com}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.bell24h.com
      
      # Security
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-bell24h-encryption-key-32-chars}
      - N8N_JWT_SECRET=${N8N_JWT_SECRET:-bell24h-jwt-secret-32-chars}
      
      # Bell24h Integration
      - BELL24H_API_URL=https://www.bell24h.com/api
      - BELL24H_API_KEY=${N8N_API_KEY:-bell24h-n8n-api-key-2024}
      - BELL24H_WEBHOOK_SECRET=${N8N_WEBHOOK_SECRET:-bell24h-webhook-secret-2024}
      
      # Email Configuration
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - N8N_SMTP_PORT=${SMTP_PORT:-587}
      - N8N_SMTP_USER=${SMTP_USER:-noreply@bell24h.com}
      - N8N_SMTP_PASS=${SMTP_PASS:-your-app-password}
      - N8N_SMTP_SENDER=${SMTP_SENDER:-Bell24h <noreply@bell24h.com>}
      
      # Logging
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console,file
      
      # Performance
      - N8N_METRICS=true
      - N8N_DIAGNOSTICS_ENABLED=true
      
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-workflows:/home/node/.n8n/workflows
      - ./n8n-credentials:/home/node/.n8n/credentials
    depends_on:
      - postgres
      - redis
    networks:
      - bell24h-network

  postgres:
    image: postgres:15-alpine
    container_name: bell24h-n8n-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${N8N_DB_NAME:-n8n}
      - POSTGRES_USER=${N8N_DB_USER:-n8n}
      - POSTGRES_PASSWORD=${N8N_DB_PASSWORD:-n8n-password}
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data
    networks:
      - bell24h-network

  redis:
    image: redis:7-alpine
    container_name: bell24h-n8n-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - n8n_redis_data:/data
    networks:
      - bell24h-network

  nginx:
    image: nginx:alpine
    container_name: bell24h-n8n-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/n8n.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - n8n
    networks:
      - bell24h-network

volumes:
  n8n_data:
  n8n_postgres_data:
  n8n_redis_data:

networks:
  bell24h-network:
    driver: bridge
