[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = ".netlify/functions"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images"
  status = 200
  query = { url = ":url", w = ":width", q = ":quality" }

[[redirects]]
  from = "/_ipx/*"
  to = "/.netlify/images"
  status = 200
  query = { url = ":url", w = ":width", q = ":quality" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
