[build]
builder = "nixpacks"
buildCommand = "npm ci --legacy-peer-deps && npx prisma generate && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
