version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Uncomment if needed
      # - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      # - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - bell24h-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=bell24h
      - POSTGRES_PASSWORD=bell24h_secure_password
      - POSTGRES_DB=bell24h
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bell24h-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bell24h"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  bell24h-network:
    driver: bridge

volumes:
  postgres-data: