name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Lint check
      - name: Check code style
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      # Type check
      - name: Check TypeScript
        run: npx tsc --noEmit

      # Run tests in CI mode
      - name: Run tests
        run: npm test
        env:
          NODE_ENV: test
          CI: true

  preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Build the application
      - name: Build
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL_STAGING }}

      # Deploy to Render preview environment
      - name: Deploy Preview
        uses: JorgeLNJunior/render-deploy@v1.4.3
        with:
          service_id: ${{ secrets.RENDER_PREVIEW_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      # Comment on PR with preview URL
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Preview deployment
          
      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Preview deployment
            
            🚀 Your changes have been deployed to the preview environment!
            
            Preview URL: https://${{ github.event.pull_request.number }}-bell24h-preview.onrender.com
            
            *Note: It may take a few minutes for the changes to be visible.*
          edit-mode: replace