name: Deployment Protection

on:
  push:
    branches: [main, staging, develop]
  pull_request:
    branches: [main]

jobs:
  protect:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Build project
      run: npm run build
      
    - name: Verify protected files
      run: node scripts/protect-files.js verify
      
    - name: Check deployment lock
      run: |
        if [ -f ".deployment-lock" ]; then
          locked=$(cat .deployment-lock | jq -r '.locked')
          if [ "$locked" = "true" ]; then
            echo "❌ Deployment is locked!"
            exit 1
          fi
        fi
        
    - name: Create backup
      if: github.ref == 'refs/heads/main'
      run: node scripts/backup.js